language: java

#sudo: required

#services:
#  - docker

#before_install:
#  - docker build -t rbarajasd/my-app -f Dockerfile.dev .

script:
  - ./gradlew build

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "gradle-project-001"
  env: "Gradleproject001-env"
  bucket_name: "gradle-project-bucket"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"