FROM gradle:7.0.2-jdk8 AS build

WORKDIR /usr/app

COPY --chown=gradle:gradle . /usr/app

RUN gradle build --no-daemon

FROM openjdk:15-jdk-alpine

COPY --from=build /usr/app/build/libs/gradle-project-0.0.1-SNAPSHOT.jar /usr/app/app.jar

CMD ["java","-jar","/usr/app/app.jar"]